CREATE DATABASE FINANCIALCONSUMER;
-- DROP TABLE FINANCIALCONSUMER.DATA_FINANCE;
SHOW DATABASES;
USE FINANCIALCONSUMER;

-- 1. FINANCIALCONSUMER 데이터베이스의 DATA_FINANCE 테이블
-- 테이블 생성 : 컬럼명, 데이터 형식, NULL 허용, 기본값, 기본키 컬럼 선언
CREATE TABLE FINANCIALCONSUMER.DATA_FINANCE (
	NUM_SERIAL INT NOT NULL PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL,
    GENDER VARCHAR(10),
    AGE INT,
    PHONE_NUMBER VARCHAR(20),
    ZIP_CODE INT,
    HOME_ADDRESS VARCHAR(100),
    HOME_TYPE VARCHAR(10),
    INCOME_BRACKET INT,
    CREDIT_SCORE INT,
    REPAYMENT_RISK_INDEX INT,
    AMT_CREDITCARD_PAYMENT INT,
    AMT_CASHADVANCE_PAYMENT INT,
    NUM_CREDITCARD_ISSUANCES INT,
    NUM_CREDITCARD_CANCELED INT,
    TF_LOAN BOOLEAN,
    AMT_CREDITLOAN INT,
    AMT_CREDITLOAN_OUTSTANDING INT,
    TF_PENSION BOOLEAN,
    AMT_PENSION INT
) ENGINE=MYISAM CHARSET=utf8;

-- 로컬 대용량 데이터 파일 로드
LOAD DATA LOCAL INFILE 'C:/Program Files/MySQL/MySQL Server 8.0/Uploads/DATA_FINANCE.csv'
IGNORE INTO TABLE FINANCIALCONSUMER.DATA_FINANCE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
STARTING BY ''
IGNORE 1 ROWS;


-- 2. FINANCIALCONSUMER 데이터베이스의 DATA_JOIN_CARDPAYMENT 테이블
CREATE TABLE FINANCIALCONSUMER.DATA_JOIN_CARDPAYMENT (
	NUM_SERIAL INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(10) NOT NULL,
		GENDER VARCHAR(10),
    PHONE_NUMBER VARCHAR(20),
    BIRTH_DATE DATETIME,
    PAYMENT_DATE DATETIME,
    AMT_CREDITCARD_PAYMENT INT,
    AFFILIGATESTORE_ADDRESS VARCHAR(100),
    AFFILIGATESTORE_INDUSTRY_CODE VARCHAR(10),
    AFFILIGATESTORE_INDUSTRY_TYPE VARCHAR(20)
) ENGINE=MYISAM CHARSET=utf8;

LOAD DATA LOCAL INFILE 'C:/Program Files/MySQL/MySQL Server 8.0/Uploads/DATA_JOIN_CARDPAYMENT.csv'
IGNORE INTO TABLE FINANCIALCONSUMER.DATA_JOIN_CARDPAYMENT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
STARTING BY ''
IGNORE 1 ROWS;

-- DATETIME에서 DATE로 형변환
ALTER TABLE DATA_JOIN_CARDPAYMENT MODIFY BIRTH_DATE DATE NULL;
ALTER TABLE DATA_JOIN_CARDPAYMENT MODIFY PAYMENT_DATE DATE NULL;

-- 데이터베이스 내 테이블의 각 컬럼(속성) 확인
DESC DATA_JOIN_CARDPAYMENT;
-- 테이블의 컬럼명, 타입, 결측 여부 등 변경
-- ALTER TABLE DATA_JOIN_ACCOMODATIONAPP RENAME COLUMN 일련번호 TO NUM_SERIAL;

-- 데이터 5행 조회
SELECT *
-- COUNT(*)
FROM DATA_JOIN_CARDPAYMENT
-- DATA_FINANCE
LIMIT 5;